### ISSUE TITLE
PMIx v4 Planning

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix-standard#189]
Planned additions:
- [x] PMIx Groups: support for dynamic construction/destruction of process “groups”. Mostly targeting the MPI Sessions and data analytics areas (done)

- [x] Attribute support reporting: ability for host environment to register the attributes they support, and for users to query the list of supported attributes (both by the PMIx library and host) for each API (done)

- [x] Scheduler interfaces for accessing fabric information (e.g., communication costs) (done)

- [ ] Scheduler interfaces for storage interactions (e.g., retrieval time estimates)

- [x] Definition of pmix_coord_t structure and support (done)
        - [x] Extend struct and add macros (#212) (done)

- [x] Completion of tool support

- [x] Clarify intent of cbdata in function signatures (#184)(#214)

- [x] Clarify use of request-related attributes (#185)

- [x] Clarify purpose of PMIX_JOB_CTRL_ID (#186)(#214)

- [x] Add blocking form of PMIx_Query_info (#209) (done)

- [x] Support return of static values for PMIx_Get (#210)

- [x] Clarify regular expression generator output (#211)

"How-to" chapters:

- [x] Construct a PMIx-based tool and what you can do with one

- [x] Utilize the PMIx APIs to implement "instant on" support

Appendices:

- [x] Python bindings appendix (#180)

- [x] Argv and other convenience macros (#213)

**Comment by rhc54** [comment]
Timing will be coordinated with https://github.com/pmix/pmix/issues/1256

**Comment by jjhursey** [comment]
Refs:
 * Scheduler interfaces PR: https://github.com/pmix/pmix-standard/pull/202
 * (merged) pmix_coord_t struct: https://github.com/pmix/pmix-standard/pull/165

**Comment by jjhursey** [comment]
OpenPMIx Issue to track last remaining PMIx v4 standard items:
 * https://github.com/openpmix/openpmix/issues/1696
