### ISSUE TITLE
PMIx v3.2 Checklist

### ISSUE THREAD

**Issue by jjhursey** [pmix/pmix-standard#270]
Below is a checklist for v3.2 items that need to be completed before we can release this errata version.

- [x] Update history https://github.com/pmix/pmix-standard/pull/220
- [x] Update Acknowledgements
- [x] Add document checker from master PR #268
- [x] Add watermark for unofficial drafts PR #229
- [x] Clarify regular expression generator output PR #211

Some notes for this release:
 * I would like to keep this errata small if we can - especially in light of the pending release of v4. So I'm only including the things that we think we absolutely need to clarify.
 * We should release this before the v4.0 standard. Maybe approve it during the 4Q2020 ASC meeting if possible.
 * I'm hoping to have a release candidate ready by Aug. 27, 2020.

**Comment by jjhursey** [comment]
I should have a PR up for most of this in a little bit.

**Comment by jjhursey** [comment]
PR #271 contains the bulk of the changes. We need to review the Acknowledgements still.

**Comment by jjhursey** [comment]
https://github.com/pmix/pmix-standard/releases/tag/v3.2
