### ISSUE TITLE
Defining a PMIx ABI

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix-standard#365]
### Overview

The community believes that it would benefit users of PMIx if we define a standard ABI that compliant implementations must provide and ensure remains stable across versions.

### Motivation

Implementation-agnostic products (e.g., debuggers) are typically compiled against one implementation, but are designed to work against whatever implementation is installed on the target system. This is done by using the combination of `dlopen` and `dlsym `to load the library and access its public APIs.

Key to utilizing this approach is the definition of a standardized ABI that is well-characterized and stable between both implementations and releases of each implementation. This issue has been created to identify the steps required to accomplish that goal, and to track progress in achieving it.

### Stages

- [x] Define what "ABI" means in the context of PMIx (see #364)
- [x] Define fixed values for PMIx error constants (see #359)
- [x] Define fixed values for non-error constants like `PMIX_ALLOC_NEW` (see #359)
- [x] Decide on values for PMIx constant boundaries (e.g., `PMIX_DATA_TYPE_MAX`) (see #394)
        - PMIX_EVENT_SYS_BASE
        - PMIX_EVENT_SYS_OTHER
        - PMIX_PROC_STATE_UNTERMINATED
        - PMIX_PROC_STATE_TERMINATED
        - PMIX_PROC_STATE_ERROR
        - PMIX_JOB_STATE_UNTERMINATED
        - PMIX_JOB_STATE_TERMINATED
        - PMIX_JOB_STATE_TERMINATED_WITH_ERROR
        - PMIX_EXTERNAL_ERR_BASE
        - PMIX_DATA_TYPE_MAX
        - PMIX_ALLOC_EXTERNAL
- [x] Review/revise the `pmix_proc_t` definition to be more memory footprint friendly (#366)
   - Revise PMIX_MAX_NSLEN?
   - Convert `pmix_nspace_t` type to a `char*` pointer?
   - No changes to these structures is being proposed.
- [x] Review/revise the PMIx `key` usage to be more memory footprint friendly, e.g., when used in a `pmix_info_t` structure (#367)
   - Revise PMIX_MAX_KEYLEN?
   - Convert `pmix_key_t` to a `char*` pointer?
  - No changes to these structures is being proposed.
- [x] Scrub the Standard doc to clarify who (application or PMIx library) retains responsibility for releasing memory in revised `pmix_proc_t` and `pmix_info_t` structures should they be modified from current definition - probably would need to be done on an API-by-API basis
  - No changes to these structures is being proposed.
- [x] Review/revise the `data` union on the `pmix_value_t` structure - should we limit the size to `sizeof(void*)` by changing any larger elements to pointers? (#399)
  - Current impact would be to:
    - float
    - double
    - struct timeval
    - time_t
    - pmix_envar_t
- [x] Create standardized PMIx ABI headers (see https://github.com/pmix/pmix-abi)
    - public repo is now available
* [x] Review item #446 
* [x] Review item #448
* [x] The last thing to do is set the version relationships in the [pmix-abi](https://github.com/pmix/pmix-abi) repo when we release v5.0

**Comment by jjhursey** [comment]
Related PRs on general ABI language for iteration:
 * Governance: https://github.com/pmix/governance/pull/34
 * Standard: https://github.com/pmix/pmix-standard/pull/375

**Comment by jdinan** [comment]
Two issues related to ABI compatibility that I would like to raise:
1. Version checking -- We need version numbers that we can capture at compile time and compare with version numbers queried from a dynamically loaded PMIx library. IIUC today these are strings, which require string parsing to achieve this (this is bad). We also need a clear ABI guidelines so that we can determine when the dynamically loaded library is compatible. E.g., same major version and same or greater minor version is compatible.
2. Functions implemented as macros -- You can't dlopen a macro. I had to write a shim library for PMIx to absorb the macros and add a function that I can dlopen. If PMIx wants to support dlopen fully, it needs a symbol for every function.

**Comment by rhc54** [comment]
> 1. Version checking -- We need version numbers that we can capture at compile time and compare with version numbers queried from a dynamically loaded PMIx library. IIUC today these are strings, which require string parsing to achieve this (this is bad).

I'm not entirely sure what you mean here, Jim. Here is what we currently provide:

In the pmix_version.h header:
```
/* define PMIx version */
#define PMIX_VERSION_MAJOR 5L
#define PMIX_VERSION_MINOR 0L
#define PMIX_VERSION_RELEASE 0L

#define PMIX_NUMERIC_VERSION 0x00050000
```

As an API:
```
/* Get the PMIx version string. Note that the provided string is
 * statically defined and must NOT be free'd  */
PMIX_EXPORT const char* PMIx_Get_version(void);
```
A number of projects use the header file at configure time to detect compatibility and protect pieces of code (via `#if` clauses) as required. The API version returns the typical MAJOR.MINOR.RELEASE triplet you get from most projects.

Is something else required?

> We also need a clear ABI guidelines so that we can determine when the dynamically loaded library is compatible. E.g., same major version and same or greater minor version is compatible.

That's getting pretty down into the business of the individual implementations, isn't it? There isn't any general rule or even common practice for how one sets major/minor numbers. OpenPMIx uses the libtool conventions, so major/minor would suffice - but other projects do things in very different ways. I don't see how one can mandate such a thing.

> Functions implemented as macros -- You can't dlopen a macro. I had to write a shim library for PMIx to absorb the macros and add a function that I can dlopen. If PMIx wants to support dlopen fully, it needs a symbol for every function.

Welllll...yes and no. I reiterate what I've said multiple times. The macros are _convenience_ macros - nobody is forced to use them to perform any action. Since they _only_ get expanded at compile time, they have zero impact on the dlopen question as the *macro* isn't in the compiled library - it's the underlying *binary* that is present. In other words, you can write your program without the macros by simply replacing the macro with the corresponding code - yeah, a little less convenient, but that's why they are called "convenience macros".

I have written several dlopen-based programs now that don't use any of the macros, and they work just fine. True, I had to write code to perform what could have been done with a one-line macro - but that was my _choice_ as an implementer because I was trying to prove I could compile the program without referencing any PMIx header. It wasn't something dictated by the Standard. We only define the macros so that implementations can provide the convenience for those compiling against them, should they choose to do so.

I used the results of those test programs to guide the first-cut at the community's ABI header.  Most of the macros are implemented as simple code directly in the header - e.g., `PMIX_LOAD_PROCID` just does some simple `memcpy` and assignments. There is no need for those to become a function - we just keep them in the ABI header and people can use them _if they so choose_.

There are a few macros we have identified that currently call non-standard backend functions. We have agreed to replace the backend functions with official APIs as (a) those macros are definitely useful, and (b) the functional form is easy to implement. I suspect we will keep the macros in the ABI header, but have them call the new API backend functions.

**Comment by jdinan** [comment]
> PMIX_VERSION_*

Thanks, this is half of what we need. I had only looked at the spec and I'm not finding the constants you mentioned there.

> As an API

I would also need an API to query the same version numbers as above from the library that I'm dynamically linked with and a way to determine whether the dynamically linked library supports the compile time library's ABI.

If you want version numbering and ABI compatibility to be an implementation choice, a simple approach would be add a function like `pmix_are_these_versions_compatible(int build_version_major, int build_version_minor, int build_version_release, int link_version_major, int link_version_minor, int link_version_release)`. You can get more sophisticated from here if you wanted to, e.g. providing the version to the PMIx library at initialization time to request a specific ABI.

It looks like PMIx is already close to requiring semantic versioning (https://semver.org/) (which I would regard as a good thing).

> Functions as macros

I would need a guarantee from PMIx that pasting the macros into my code is valid. E.g. if the macros access specific fields in structures, they would need to be part of the spec. Or, if structures need to be allocated/accessed/initialized in a particular way, that also needs to be specified. I don't have any specific examples of cases of concern, so these are just general concerns. The non-standard backend functions are the most problematic thing, glad you are already aware of this.

**Comment by rhc54** [comment]
> Thanks, this is half of what we need. I had only looked at the spec and I'm not finding the constants you mentioned there.

Fair enough - they might not be in the Standard. Should be added.

> I would also need an API to query the same version numbers as above from the library that I'm dynamically linked with and a way to determine whether the dynamically linked library supports the compile time library's ABI.

Hmmm...I think there may be some misunderstanding/confusion here, so let me try to help clarify. The version numbers I cited are all _library_ version values - not the version of the Standard that the library supports. OpenPMIx used to try and keep the two in-sync, but that proved impossible to do without abandoning the libtool convention (and totally confusing the downstream packagers). So we added other values that indicate the version of the Standard that this particular release tracks. These are not currently exposed, though I suppose they could be - but they have limited utility (as I shall now explain).

That said, even those new version numbers are less-than-helpful. The Standard doesn't _require_ an implementation to support any particular API or attribute - it only stipulates that _if_ you do provide it, _then_ the behavior and signature must match the specified one. This is typical of standards in general - e.g., it is quite common for MPI implementations to leave out functions (e.g., MPI_Comm_spawn) that they don't support.

Thus, the only real way to deal with compatibility when using `dlopen` is to use `dlsym` to look for the function - if it returns `NULL`, then the library you are connecting with doesn't provide it. This could happen regardless of the library's version number (or version of the Standard they claim to support), so you always have to protect yourself.

> I would need a guarantee from PMIx that pasting the macros into my code is valid. E.g. if the macros access specific fields in structures, they would need to be part of the spec. Or, if structures need to be allocated/accessed/initialized in a particular way, that also needs to be specified.

I don't know how to phrase such a guarantee other than providing the official macro version in the ABI header. The macro implementations in a given library are left to the implementers - however, the structures are all clearly defined in the Standard. You can initialize/allocate those structures any way you want - again, the macro is purely there for convenience.

So let me be clear about these macros. I originally put them in the headers because (a) I used them extensively inside the library, and (b) early-adopters begged me to make them accessible so they could use them too. In the words of one such person, "they are just so darned convenient!". Hence the term "convenience macro". We subsequently included them in the Standard to ensure that those projects that had already used them wouldn't have a problem should some other implementation appear down the road.

Of course, we cannot _require_ that they provide the macro - just as we cannot _force_ them to provide a given API. Still, one hopes that pressure from the existing code base would suffice to motivate an implementation to include them.

> The non-standard backend functions are the most problematic thing, glad you are already aware of this.

Yep - since nobody has touched the ABI header after my first-cut, looks like I'll have to do it. Sigh.

**Comment by jdinan** [comment]
The problem that I need to solve is: I have a binary package foo that is built against some PMIx implementation barpmix-1.0. The version v1.0 is the barpmix version and has no relation to the PMIx standard version numbering. The user installs foo and also installs barpmix-1.1. Does foo work?

With regard to APIs being optional, I would hope this is sorted out by the compiler. It should not be the case that APIs are declared in the `barpmix.h` header and then not present in `libbarpmix.so`. Although, I have been thinking only about ABI compatibility for a single PMIx client library. Is the goal of ABI compatibility that two completely different implementations of PMIx should be ABI compatible?

**Comment by rhc54** [comment]
> The problem that I need to solve is: I have a binary package foo that is built against some PMIx implementation barpmix-1.0. The version v1.0 is the barpmix version and has no relation to the PMIx standard version numbering. The user installs foo and also installs barpmix-1.1. Does foo work?

Ah, so this is a library compatibility issue! I can only speak for OpenPMIx (but then, I haven't heard a whisper of any other implementation). In our case, the short answer is "yes".

Longer answer is that your package will work with any version of libpmix that is v1.0 and above - this includes all major version changes as well. This is why the `.so` number of the library remains unchanged - the linker uses that number to determine compatibility when loading. So long as the `.so` of the library is the same as the one you compile against, the linker knows all is well.

When you use `dlopen`, you lose the linker's protection - and I, at least, am unaware of a method for dynamically learning the `.so` number of a library (if someone else does, please speak up!). I suppose we could add some symbol in the library that contains the `.so` value, assuming it isn't already there. Anyone know?

FWIW: OpenPMIx has had a `.so` number of 2 forever. I don't anticipate a reason to change. If your package can `dlsym` a particular API, then it will work. We retain all deprecated attributes and constants as well, so your program _should_ be just fine so long as you are moving forward. If you move backward, of course, a function and/or attribute may not be available in an older version - so you'd have to deal with a `dlsym` call that returns `NULL`.

> t should not be the case that APIs are declared in the barpmix.h header and then not present in libbarpmix.so

Correct - the compiler won't allow that to happen.

>  Is the goal of ABI compatibility that two completely different implementations of PMIx should be ABI compatible?

This was indeed the objective of this conversation. As was discussed here and in other related issues, this has largely already been achieved. The only remaining item is the macros that use non-API backends.

**Comment by rhc54** [comment]
I've run into a problem here that really hurts. In order to support the `dlopen/dlsym`, one must remove any API calls from the macros. The painful two we therefore lose are `PMIX_INFO_LOAD` and `PMIX_INFO_XFER`. I could convert these to function calls, but sadly they are heavily used by existing codes and this will cause a major impact.

Anyone have thoughts on this? I could retain the macros and just have them call `PMIx_Value_load` and `PMIx_Value_xfer`, but that wouldn't work for the `dlopen/dlsym` use-case.

**Comment by dsolt** [comment]
The IAWG will be hosting a discussion on this topic on Monday 1/24 @ 1pm CST.  Please see the meetings page for info.

**Comment by jdinan** [comment]
@rhc54 Is the overhead measurable in the context of e.g. an MPI job launch?

Another option that I think you mentioned earlier is to standardize the macro, including any internal functions, so that a dlopen consumer can create their own version of the macro that uses a pointer for the internal function.

**Comment by rhc54** [comment]
Not sure what overhead you are referring to here - converting the macros to functions had minimal impact as they called functions within them anyway.

Yes, we could just keep the macro in the standard, describing what it should do, and let you define it in terms of your dlsym'd function. Just couldn't include it in the `pmix-abi` header. Might be the right answer.

**Comment by jdinan** [comment]
Apologies, I saw "major impact" above and thought you were referring to performance.

IIUC, you could define `PMIX_INFO_LOAD` as a function in the `pmix-abi` header and have a symbol for it in `libpmix.so` without conflicting with a macro definition in the regular pmix header. But, I think it's less confusing to just introduce a new function that you can account for in the ABI (or standardize the macros as mentioned above).

**Comment by raffenet** [comment]
> I would also need an API to query the same version numbers as above from the library that I'm dynamically linked with and a way to determine whether the dynamically linked library supports the compile time library's ABI.
> 
> If you want version numbering and ABI compatibility to be an implementation choice, a simple approach would be add a function like:
> 
> ```
> pmix_are_these_versions_compatible(int build_version_major, int build_version_minor, int build_version_release, int link_version_major, int link_version_minor, int link_version_release)
> ```

@jdinan I brought up this sample interface up at the last quarterly meeting to try and determine if this is something we should add before we finalize the standard ABI. The general sentiment seems to be the functionality is needed. But do we actually want a binary interface query? E.g.
```c
bool pmix_binary_compatible(int binary_version);
```
After all, the goal is defining compatibility across implementations, so semantic library versioning doesn't really apply. I realize that might not have been what you were looking for when you dropped into the discussion, but you're stuck now 😄.

**Comment by raffenet** [comment]
In the event of an ABI breaking change, a `false` result would at least tell the user not to even try. At that point recompiling is the only safe path, otherwise you might be dealing with different data structure layouts or API signatures.

**Comment by rhc54** [comment]
Okaaayy...but we don't allow changes to structure layouts or API signatures in PMIx. You are required to create an entirely new thing in that scenario. So I'm still not clear what this does for us.

**Comment by raffenet** [comment]
I think that's a fine approach to take from the standard point of view, and would likely make this functionality useless. Do we need to write in any guidance/governance text to make that clear?

**Comment by rhc54** [comment]
I thought that was in a recent RFC about ABI in general? If not, then yeah - it would make sense to add it there.

**Comment by jdinan** [comment]
I just found some info on `dlvsym` by googling. I think Ralph mentioned this earlier. Can this help?

**Comment by rhc54** [comment]
> I just found some info on `dlvsym` by googling. I think Ralph mentioned this earlier. Can this help?

Only in the case where we allow the API signature to change, and that is something we really don't want to do as it causes problems for everyone (e.g., by requiring them to handle all the variations of that signature). Best to just say the symbol is "fixed" - if you need to change it for some reason, then create a replacement instead of altering it.

**Comment by jjhursey** [comment]
For debugging/reporting, it would be nice to have a query for the ABI similar to what we have to for the implementation via `PMIx_Get_version`. The user might want to display the PMIx library version, and PMIx ABI compliance version (which would be the same as the PMIx Standard compliance level? see discussion [here](https://github.com/pmix/pmix-standard/issues/364#issuecomment-990247610)).

It should be noted that it is possible to support multiple versions of an ABI in an implementation. IIRC OpenFabrics does this with their ABi. If the PMIx implementation supports different ABI levels then the user might want to know which set of ABIs are supported and request a specific one.

Functionally, we need some clarification on the use case for a `PMIx_Get_ABI_version` so we can form it correctly. I'm ok with adding it (and am willing to volunteer to do the work), but I don't have a concrete target use case in my mind just yet. That is outside of provisional items in the standard.

The few aspects where this matters would be:
 1. API signature changes.
 2. Data structure field changes.
 3. Constant and attribute changes.

PR https://github.com/pmix/pmix-standard/pull/375 has some of the working guidance on the ABI.

### API Signature Changes

`dlsym` checks for the function name, but does not check the function signature. If the signature of an existing API ever changed then we need some ABI detection so the end-user knows which function pointer signature to use with the pointer returned by `dlsym`.

I advocate that we do not change the existing function signatures of **stable APIs**.

However, **provisional APIs** live in a more generous definition. The goal of provisional additions to the standard was to get a feature in front of users to experiment with early with the understanding that it may change in the future before becoming 'stable'. So it is possible that that experimentation turns up the need for an API change. At this point knowing which version you are using would be important.

### Data Structure Changes

A (very) few data structures can be appended to between versions of the standard. The `pmix_value_t` is a good example of that situation.

I advocate that we do not change the size of existing data structures. The `pmix_value_t` is an interesting use case since it is composed of a `union` of data types. So we can set a fixed size via padding for this union that no new additions are allowed to exceed.

For those structures, the caller might need to know if a new field is going to be recognized by the PMIx library.

Provisional throws a bit of a wrinkle in this as well. If a provisional change adds a new data structure then that data structure might change between iterations of the standard. However, to be useful, the data structure needs to be paired with an API that accepts it. So if the library does not define the function `PMIx_newfoo` then it has no opportunity to accept the new datatype that is an argument to `PMIx_newfoo`. Again the exception to this is `pmix_value_t` where a provisional addition might add a new value type to the union which the application expects something like `PMIx_Query_info` to fill in.

I don't have a strong use case here though.

### Constant and Attribute Changes

These are defined in the header at compile time. The PMIx library can choose a runtime if they accept/support these.

The only scenario where I could see knowing the ABI would be important here is if we change the value associated with the constant/attribute. So the application compiled against ABI X with a constant defined as `12` running against an PMIx library supporting ABI Y with the same constant defined as `99` would need to know this difference.

For stable constants/attributes, this is not likely to be a problem. But for provisional constants/attributes, this is a much more common case as the interface is exercised.

## A few notes about `dlvsym`

The difference between `dlsym` and `dlvsym` is that the latter takes a version string to check against and the latter is a GNU extension. Below taken from [here](https://man7.org/linux/man-pages/man3/dlsym.3.html):
```
       #include <dlfcn.h>

       void *dlsym(void *restrict handle, const char *restrict symbol);

       #define _GNU_SOURCE
       #include <dlfcn.h>

       void *dlvsym(void *restrict handle, const char *restrict symbol,
                    const char *restrict version);
```

It doesn't seem that the version string is tied to the semantic versioning of the library (shown in the `.so` version). it is defined in the declaration of the function itself (source versioned).

What we could do is add these markers to the PMIx ABI tied to the ABI of the standard. Would we label the API with the version where it is first introduced or label the API with the version of the ABI that we are shipping with the standard? I'm assuming the latter would be more useful.

I found a good discussion of `dlvsym` in [this post](https://blog.fesnel.com/blog/2009/08/25/preloading-with-multiple-symbol-versions/). And RedHat has a [nice page](https://developers.redhat.com/blog/2019/08/01/how-the-gnu-c-library-handles-backward-compatibility#change_your_abi_with_compatibility) describing the mechanics of doing this.

**Comment by jjhursey** [comment]
Below is the current summary of the state of the ABI developments:

#### Constants:
 - https://github.com/pmix/pmix-standard/pull/359
   * State: DONE
 - https://github.com/pmix/pmix-standard/pull/394
   * State: Needs review

#### Macros (+ static inline functions)
 - https://github.com/pmix/pmix-standard/pull/383
   * State: In process - Ready for 2nd vote
 - https://github.com/pmix/pmix-abi/issues/5
   * State: Needs discussion

#### Compatibility Query
 - https://github.com/pmix/pmix-standard/issues/365#issuecomment-1005793557
   * State: Needs discussion and use case

#### Data Structures:
  * State: Nothing to do

#### Functions:
  * State: Nothing to do

#### Signedness of char (+ hetero systems)
  * State: Nothing to do

**Comment by jjhursey** [comment]
Per PMIx ASC meeting on March 10, 2022 regarding `PMIx_Get_ABI_version`
 * Instead of creating a new function `PMIx_Get_ABI_version` we could try to re-use `PMIx_Query_info` similar to how we use it for `PMIX_QUERY_ATTRIBUTE_SUPPORT`. The idea would be to create a new attribute `PMIX_QUERY_ABI_SUPPORT` that would return the ABI level supported by the library. It's possible that it could return a list of ABI levels supported, if appropriate. If more than one ABI is supported then the ABI level desired could be specified in the `PMIx_Init` info list.
 * (Josh) Setup a small example of an API that uses the version marking extension and `dlvsym`. Use this as a template and as a means of testing compiler support.

**Comment by jjhursey** [comment]
I created an example of using the `dlvsym` with a shared library. Take a look if you are interested:
 * https://github.com/jjhursey/dlvsym-example

I've found that Mac OS doesn't like the inline `.symver` so you will need a Linux box to compile.

**Comment by jjhursey** [comment]
Note from IA WG meeting on March 14, 2022:
 * Handling of `static inline` functions is discussed in https://github.com/pmix/pmix-abi/issues/5 . The PR https://github.com/pmix/pmix-abi/pull/6 seems like an acceptable approach. The WG will review the PR.
 * @dsolt will take a look at the `pmix_value_t` to determine (1) the current size of the structure, and (2) if any padding is required for the ABI effort.
 * @jjhursey will close Issues #366 (`pmix_nspace_t`) and #367 (`pmix_key_t`) tickets with the notes for the prior IA WG meeting.
 * Provisional interfaces are a compelling use case for exposing the ABI version to the end user.
 * The `dlvsym` approach is interesting but is probably not as portable as it needs to be for this ABI effort. Additionally, it only handles the C interfaces so a different solution would be needed for the other language bindings (i.e., Python). We may play around with it some more as an option for libraries that want a flexible way to provide old bindings for things like Provisional interfaces.
 * The `PMIx_Query_info` direction seems the most promising for exposing the ABI version. It should be noted that if we choose to use `PMIx_Query_info` for accessing this information then that function becomes 'ultra stable' since there would be no mechanism for the caller to know that the signature of `PMIx_Query_info` may have changed. This is acceptable since (1) the API is already quite flexible and (2) it is a stable API so even if it is deprecated/removed it would not be replaced in the future.
   * @jjhursey will take a pass at defining this in a PR for discussion.

**Comment by jjhursey** [comment]
I posted the PR to create a `PMIX_QUERY_ABI_VERSION` attribute. I'll work on some example code and implementation over the next week. In the meantime take a look at the PR to see if we need anything further.
 * https://github.com/pmix/pmix-standard/pull/397

**Comment by jjhursey** [comment]
Note from IA WG meeting on March 28, 2022:
 * @dsolt will take a look at the pmix_value_t to determine (1) the current size of the structure, and (2) if any padding is required for the ABI effort.
 * @raffenet Will investigate ABI Compliance checker tool (per https://github.com/pmix/pmix-abi/issues/7) to see if it can be used to check the ABI
 * @jjhursey Complete the left to do items for `PMIX_QUERY_ABI_VERSION` https://github.com/pmix/pmix-standard/pull/397#issuecomment-1067462862

**Comment by rhc54** [comment]
Take a close look at `pmix_value_t` in prior versions as well as the current one. I can't swear that we didn't change the `nspace` field to a pointer (from a `pmix_nspace_t` object itself) at some time in the past, though I think (hope?) we caught it prior to a release.

**Comment by jjhursey** [comment]
Note from IA WG meeting on April 4, 2022:
 * Ken demo'ed the ABI Compliance checker tool. Some work left to do, but generally good. It would be helpful to have as a CI or 'make' target.
 * Reviewed the `pmix_value_t` size. `sizeof(pmix_value_t) = 32 bytes` (`data` union is `24 bytes`, `type` is `2 bytes`).
   * Suggested that instead of padding we add the wording that (or something close to): "Changes to pmix_value_t should not affect the size of this type on a given platform. Recommend adding a pointer to a structure in the data union if that structure will exceed the current size of the pmix_value_t structure."
 * Josh will finish up the `PMIX_QUERY_ABI_VERSION` example and post a version later this week.
 * The announcement deadline for the next quarterly meeting is April 12, 2022. So we will use part of the next IAWG meeting (April 11) to make sure all of the ABI PRs are ready to go.

**Comment by jjhursey** [comment]
I completed the work on the `PMIX_QUERY_ABI_VERSION` key:
 * PMIx Standard PR: https://github.com/pmix/pmix-standard/pull/397
 * OpenPMIx implementation: https://github.com/openpmix/openpmix/pull/2551
 * PMIx ABI Example: https://github.com/pmix/pmix-abi/pull/10

**Comment by jjhursey** [comment]
Breakdown of the current `pmix_value_t` from OpenPMIx `master` to get a feeling for sizes.
 * `value.c` : https://gist.github.com/jjhursey/07933aacb76de9419902f53c4e7d74f7

The structure looks like:
```
typedef struct pmix_value {
    pmix_data_type_t type;
    union {
      ... Bunch of fields
    } data;
} pmix_value_t;
```

The breakdown is:
```
pmix_value_t : 32
-------------:-------
pmix_value_t :  2 type
pmix_value_t : 24 data
-------------:-------
pmix_value_t :  1 (.flag)
pmix_value_t :  1 (.byte)
pmix_value_t :  8 (.string)
pmix_value_t :  8 (.size)
pmix_value_t :  4 (.pid)
pmix_value_t :  4 (.integer)
pmix_value_t :  1 (.int8)
pmix_value_t :  2 (.int16)
pmix_value_t :  4 (.int32)
pmix_value_t :  8 (.int64)
pmix_value_t :  4 (.uint)
pmix_value_t :  1 (.uint8)
pmix_value_t :  2 (.uint16)
pmix_value_t :  4 (.uint32)
pmix_value_t :  8 (.uint64)
pmix_value_t :  4 (.fval)
pmix_value_t :  8 (.dval)
pmix_value_t : 16 (.tv)
pmix_value_t :  8 (.time)
pmix_value_t :  4 (.status)
pmix_value_t :  4 (.rank)
pmix_value_t :  8 (.nspace)
pmix_value_t :  8 (.proc)
pmix_value_t : 16 (.bo)
pmix_value_t :  1 (.persist)
pmix_value_t :  1 (.scope)
pmix_value_t :  1 (.range)
pmix_value_t :  1 (.state)
pmix_value_t :  8 (.pinfo)
pmix_value_t :  8 (.darray)
pmix_value_t :  8 (.ptr)
pmix_value_t :  1 (.adir)
pmix_value_t : 24 (.envar)
pmix_value_t :  8 (.coord)
pmix_value_t :  1 (.linkstate)
pmix_value_t :  1 (.jstate)
pmix_value_t :  8 (.topo)
pmix_value_t :  8 (.cpuset)
pmix_value_t :  2 (.locality)
pmix_value_t :  8 (.geometry)
pmix_value_t :  8 (.devtype)
pmix_value_t :  8 (.devdist)
pmix_value_t :  8 (.endpoint)
pmix_value_t :  8 (.dbuf)
pmix_value_t :  8 (.pstats)
pmix_value_t :  8 (.dkstats)
pmix_value_t :  8 (.netstats)
pmix_value_t :  8 (.ndstats)
```

Summary:
 * `pmix_value_t` is 32 bytes
 * The `data` union is `24` bytes.
   * The `.envar` element of that union is determining the size.

For reference:
```
typedef struct {
    char *envar;
    char *value;
    char separator;
} pmix_envar_t;
```

```
-------------:-------
pmix_envar_t : 24
-------------:-------
pmix_envar_t :  8 (.envar)
pmix_envar_t :  8 (.value)
pmix_envar_t :  1 (.separator)
```

**Comment by jjhursey** [comment]
Per IAWG Meeting April 11, 2022:
 * Josh: Finish evaluation of adding padding for `pmix_value_t` and email results to the mailing list
 * Josh: Work on Linker vs Build ABI wording per https://github.com/pmix/pmix-standard/issues/364#issuecomment-1095451068
 * Ken: Continue working on the ABI Compliance cheker tool per https://github.com/pmix/pmix-abi/issues/7#issuecomment-1093354044

**Comment by jjhursey** [comment]
Below is the current summary of the state of the ABI developments:

#### High Level
 - https://github.com/pmix/pmix-standard/issues/364
   * State: Added language to https://github.com/pmix/pmix-standard/pull/375
 - https://github.com/pmix/pmix-standard/pull/375
   * State: In process - Ready for Reading
 - https://github.com/pmix/governance/pull/34
   * State: In process - Ready for Reading
 - https://github.com/pmix/pmix-standard/issues/366
   * State: DONE (nothing to do)
 - https://github.com/pmix/pmix-standard/issues/367
   * State: DONE (nothing to do)
 - https://github.com/pmix/pmix-standard/issues/399
   * State: Added language to https://github.com/pmix/pmix-standard/pull/375

#### Constants:
 - https://github.com/pmix/pmix-standard/pull/359
   * State: DONE
 - https://github.com/pmix/pmix-standard/pull/394
   * State: In process - Ready for Reading

#### Macros (+ static inline functions)
 - https://github.com/pmix/pmix-standard/pull/383
   * State: In process - Ready for 2nd vote
 - https://github.com/pmix/pmix-abi/issues/5
   * State: DONE

#### Compatibility Query
 - https://github.com/pmix/pmix-standard/issues/365#issuecomment-1005793557
   * State: In process - Ready for Reading
     - PMIx Standard: https://github.com/pmix/pmix-standard/pull/397
     - OpenPMIx Implementation: https://github.com/openpmix/openpmix/pull/2551 (merged into `master` branch)
     - PMIx ABI Example: https://github.com/pmix/pmix-abi/pull/10

#### Data Structures:
  * State: Nothing to do

#### Functions:
  * State: Nothing to do

#### Signedness of char (+ heterogeneous systems)
  * State: Nothing to do

**Comment by jjhursey** [comment]
All PMIx Governance and PMIx Standard items have been merged for the ABI.

The last thing to do is set the version relationships in the [pmix-abi](https://github.com/pmix/pmix-abi) repo when we release v5.0

**Comment by abouteiller** [comment]
#446 
#448
#447

**Comment by abouteiller** [comment]
All work completed, v5.0 and abi-1.0 have been released.
